import { GoogleGenAI } from "@google/genai";

const getAiClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const generateRendering = async (
  imageBase64: string,
  prompt: string,
  watermarkText: string
): Promise<string> => {
  const ai = getAiClient();
  
  // Clean the base64 string
  const data = imageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

  // Construct a prompt that guides the model to act as a render engine
  const fullPrompt = `
    You are a high-end 3D rendering engine. 
    Analyze the provided wireframe/viewport screenshot of a 3D assembly.
    Generate a photorealistic, studio-quality product rendering based on this composition.
    
    User details: ${prompt}
    
    Lighting: Soft studio lighting, ambient occlusion, realistic shadows.
    Materials: Realistic textures (metal, plastic, glass as appropriate).
    Background: Keep it clean or as depicted.
    
    ${watermarkText ? `IMPORTANT: Overlay the text "${watermarkText}" subtly in the bottom right corner as a watermark.` : ''}
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: data
            }
          },
          {
            text: fullPrompt
          }
        ]
      }
    });

    // Extract image from response
    // The model response might contain an image (if it generated one) or text.
    // gemini-2.5-flash-image generates images if asked properly, but the structure 
    // for *pure* image generation usually comes from `generateImages` (Imagen) or strictly checking inlineData in response.
    // However, for image-to-image (editing/rendering), standard generateContent is used.
    
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    // Fallback if no image returned (shouldn't happen with correct model/prompt)
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini Rendering Error:", error);
    throw error;
  }
};
